/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package co.com.bancolombia.service.authenticationAWS.api;

import co.com.bancolombia.service.authenticationAWS.model.AuthenticationLoginResponse;
import co.com.bancolombia.service.authenticationAWS.model.JsonApiBodyResponseErrors;
import co.com.bancolombia.service.authenticationAWS.model.LoginRequest;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-04T21:59:31.662-05:00")

@Api(value = "login", description = "the login API")
public interface LoginApi {

    @ApiOperation(value = "Petición de login por medio de AWS", nickname = "loginPost", notes = "Microservicio que consume Dynamo y Cognito con apache camel", response = AuthenticationLoginResponse.class, tags={ "authentication-service-api-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Inquery step success", response = AuthenticationLoginResponse.class),
        @ApiResponse(code = 401, message = "Invalid credentials. user or password are invalid", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/login",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<?> loginPost(@ApiParam(value = "body" ,required=true )  @Valid @RequestBody LoginRequest body);

}
