/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package co.com.bancolombia.service.S3AdminAWS.api;

import co.com.bancolombia.service.S3AdminAWS.model.GetS3Request;
import co.com.bancolombia.service.S3AdminAWS.model.JsonApiBodyResponseErrors;
import co.com.bancolombia.service.S3AdminAWS.model.S3ObjectResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-07T20:01:37.027-05:00")

@Api(value = "get", description = "the get API")
public interface GetApi {

    @ApiOperation(value = "lee un objeto de un bucket s3", nickname = "getGet", notes = "lee un objeto de un bucket s3 en aws", response = S3ObjectResponse.class, tags={ "leer-objeto-api-usuario", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Inquery step success", response = S3ObjectResponse.class),
        @ApiResponse(code = 401, message = "Unathorized. user has not permissions", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/get",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<S3ObjectResponse> getGet(@ApiParam(value = "body" ,required=true )  @Valid @RequestBody GetS3Request body);

}
